-- Manual admin orders and grouped special deliveries for delivery staff.

create type public.special_delivery_status as enum ('active', 'closed');

create table if not exists public.special_deliveries (
  id bigint generated by default as identity primary key,
  name text not null,
  notes text,
  staff_id bigint references public.users(id) on delete set null,
  status public.special_delivery_status not null default 'active',
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists special_deliveries_staff_id_idx on public.special_deliveries(staff_id);
create index if not exists special_deliveries_status_idx on public.special_deliveries(status);

create trigger special_deliveries_set_updated_at
before update on public.special_deliveries
for each row execute function public.set_updated_at();

alter table public.orders
  add column if not exists is_manual boolean not null default false,
  add column if not exists special_delivery_id bigint references public.special_deliveries(id) on delete set null;

create index if not exists orders_is_manual_idx on public.orders(is_manual);
create index if not exists orders_special_delivery_id_idx on public.orders(special_delivery_id);

alter table public.special_deliveries enable row level security;

drop policy if exists special_deliveries_select_admin_or_assigned_delivery on public.special_deliveries;
create policy special_deliveries_select_admin_or_assigned_delivery
on public.special_deliveries
for select
to authenticated
using (
  public.app_is_admin()
  or (
    public.app_current_user_role() = 'delivery'
    and staff_id = public.app_current_user_id()
  )
);

drop policy if exists special_deliveries_insert_admin_only on public.special_deliveries;
create policy special_deliveries_insert_admin_only
on public.special_deliveries
for insert
to authenticated
with check (public.app_is_admin());

drop policy if exists special_deliveries_update_admin_only on public.special_deliveries;
create policy special_deliveries_update_admin_only
on public.special_deliveries
for update
to authenticated
using (public.app_is_admin())
with check (public.app_is_admin());

drop policy if exists special_deliveries_delete_admin_only on public.special_deliveries;
create policy special_deliveries_delete_admin_only
on public.special_deliveries
for delete
to authenticated
using (public.app_is_admin());

create or replace function public.app_can_access_order(p_order_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.orders o
    left join public.users c on c.id = o.client_id
    left join public.special_deliveries sd on sd.id = o.special_delivery_id
    where o.id = p_order_id
      and (
        public.app_is_admin()
        or o.client_id = public.app_current_user_id()
        or (
          public.app_current_user_role() = 'delivery'
          and (
            (
              c.role = 'client'
              and public.app_delivery_has_zone_access(c.zone_id)
            )
            or sd.staff_id = public.app_current_user_id()
          )
        )
      )
  );
$$;

grant execute on function public.app_can_access_order(bigint) to authenticated;

drop policy if exists orders_select_accessible on public.orders;
create policy orders_select_accessible
on public.orders
for select
to authenticated
using (public.app_can_access_order(id));

drop policy if exists incidents_select_accessible on public.incidents;
create policy incidents_select_accessible
on public.incidents
for select
to authenticated
using (
  public.app_is_admin()
  or client_id = public.app_current_user_id()
  or (
    public.app_current_user_role() = 'delivery'
    and public.app_can_access_order(order_id)
  )
);

drop policy if exists incidents_insert_by_role on public.incidents;
create policy incidents_insert_by_role
on public.incidents
for insert
to authenticated
with check (
  public.app_is_admin()
  or (
    public.app_current_user_role() = 'client'
    and client_id = public.app_current_user_id()
    and exists (
      select 1
      from public.orders o
      where o.id = incidents.order_id
        and o.client_id = public.app_current_user_id()
    )
  )
  or (
    public.app_current_user_role() = 'delivery'
    and public.app_can_access_order(incidents.order_id)
    and exists (
      select 1
      from public.orders o
      where o.id = incidents.order_id
        and o.client_id = incidents.client_id
    )
  )
);
