-- Initial relational schema for Reparto (Supabase/PostgreSQL)

-- Extensions
create extension if not exists pgcrypto;

-- Enums
create type public.user_role as enum ('admin', 'client', 'delivery');
create type public.delivery_status as enum ('active', 'off', 'on_delivery');
create type public.order_status as enum ('pending', 'in_delivery', 'delivered', 'cancelled');
create type public.cancel_request_status as enum ('pending', 'approved', 'rejected');
create type public.order_cancel_source as enum ('admin', 'client');
create type public.incident_type as enum ('delayed', 'damaged', 'wrong_quantity', 'other');
create type public.incident_status as enum ('open', 'in_progress', 'resolved');
create type public.incident_priority as enum ('low', 'medium', 'high');

-- Generic updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Zones
create table public.zones (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  address text,
  delivery_days text[] not null default '{}',
  delivery_time text,
  next_delivery timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger zones_set_updated_at
before update on public.zones
for each row execute function public.set_updated_at();

alter table public.zones enable row level security;

create policy zones_select_public
on public.zones
for select
to anon, authenticated
using (true);

-- Users (admin/client/delivery)
create table public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  -- For first migration parity with current app store.
  -- Move to hashed passwords in next phase.
  password text not null,
  name text not null,
  role public.user_role not null,
  zone_id bigint references public.zones(id) on delete set null,
  phone text,
  address text,
  gps_lat numeric(9,6),
  gps_lng numeric(9,6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_gps_lat_range check (gps_lat is null or (gps_lat >= -90 and gps_lat <= 90)),
  constraint users_gps_lng_range check (gps_lng is null or (gps_lng >= -180 and gps_lng <= 180))
);

create index users_role_idx on public.users(role);
create index users_zone_id_idx on public.users(zone_id);

create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

-- Delivery profile (only for role=delivery)
create table public.delivery_staff_profiles (
  user_id bigint primary key references public.users(id) on delete cascade,
  vehicle text,
  status public.delivery_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger delivery_staff_profiles_set_updated_at
before update on public.delivery_staff_profiles
for each row execute function public.set_updated_at();

-- Products
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  unit text not null default 'unidad',
  stock integer not null default 0,
  min_stock integer not null default 0,
  price numeric(12,2) not null default 0,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_stock_non_negative check (stock >= 0),
  constraint products_min_stock_non_negative check (min_stock >= 0),
  constraint products_price_non_negative check (price >= 0)
);

create index products_category_idx on public.products(category);

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

-- Orders
create table public.orders (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.users(id) on delete restrict,
  status public.order_status not null default 'pending',
  created_at timestamptz not null default now(),
  scheduled_delivery timestamptz,
  delivered_at timestamptz,
  total_amount numeric(12,2) not null default 0,
  notes text,
  delivery_note text,
  delivery_note_at timestamptz,
  cancel_request_status public.cancel_request_status,
  cancel_requested_at timestamptz,
  cancel_decision_at timestamptz,
  cancel_source public.order_cancel_source,
  created_by bigint references public.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint orders_total_amount_non_negative check (total_amount >= 0)
);

create index orders_client_id_idx on public.orders(client_id);
create index orders_status_idx on public.orders(status);
create index orders_cancel_request_status_idx on public.orders(cancel_request_status);
create index orders_scheduled_delivery_idx on public.orders(scheduled_delivery);

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- Order items
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  created_at timestamptz not null default now(),
  constraint order_items_quantity_positive check (quantity > 0),
  constraint order_items_unit_price_non_negative check (unit_price >= 0),
  constraint order_items_unique_product_per_order unique (order_id, product_id)
);

create index order_items_order_id_idx on public.order_items(order_id);
create index order_items_product_id_idx on public.order_items(product_id);

-- Incidents
create table public.incidents (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  client_id bigint references public.users(id) on delete set null,
  type public.incident_type not null,
  status public.incident_status not null default 'open',
  description text not null,
  reported_at timestamptz not null default now(),
  resolved_at timestamptz,
  priority public.incident_priority not null default 'medium',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index incidents_order_id_idx on public.incidents(order_id);
create index incidents_status_idx on public.incidents(status);
create index incidents_priority_idx on public.incidents(priority);

create trigger incidents_set_updated_at
before update on public.incidents
for each row execute function public.set_updated_at();

-- Delivery history
create table public.delivery_history (
  id bigint generated by default as identity primary key,
  staff_id bigint not null references public.users(id) on delete restrict,
  zone_id bigint references public.zones(id) on delete set null,
  date timestamptz not null default now(),
  items_count integer not null default 0,
  distance_km numeric(8,2),
  time_spent text,
  created_at timestamptz not null default now(),
  constraint delivery_history_items_count_non_negative check (items_count >= 0)
);

create index delivery_history_staff_id_idx on public.delivery_history(staff_id);
create index delivery_history_zone_id_idx on public.delivery_history(zone_id);

-- Convenience views for current app shape
create or replace view public.clients_v
with (security_invoker = true) as
select
  u.id,
  u.email,
  u.name,
  u.role,
  u.zone_id as zone,
  u.phone,
  u.address,
  u.gps_lat as "gpsLat",
  u.gps_lng as "gpsLng",
  u.created_at
from public.users u
where u.role = 'client';

create or replace view public.delivery_staff_v
with (security_invoker = true) as
select
  u.id,
  u.name,
  u.zone_id as "zoneId",
  u.email,
  u.phone,
  p.vehicle,
  p.status,
  u.created_at
from public.users u
join public.delivery_staff_profiles p on p.user_id = u.id
where u.role = 'delivery';
